adam<-function(){
  message(" --------------------------")
  message(" Thoughthful Akika")
  message(" always giving aid and help")
  message(" improving our team.")
  message(" --------------------------")
  message("    \\ ")
  message("      \\ ")
  message("        \\ ")
  message("            |\\___/| ")
  message("          ==) ^Y^ (==")
  message("            \\  ^  /")
  message("             )=*=(")
  message("            /     \\")
  message("            |     |")
  message("           /| | | |\\")
  message("           \\| | |_|/\\")
  message("           //_// ___/")
  message("               \\_)")
  message("")

}
